
- name: Update Windows Server and Reboot if Needed
  hosts: windows
  gather_facts: yes
  vars:
    ansible_python_interpreter: ~/.local/pipx/venvs/pywinrm/bin/python  # Path to Python executable in pipx
  tasks:
    - name: Install pending Windows updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: yes
